export const activeConnectors = [
  {
    id: "amplitude",
    name: "Amplitude",
    description: "Product analytics — events, funnels, cohorts, retention",
    bg: "bg-blue-100",
    color: "text-blue-700",
    letter: "A",
    lastSynced: "2 minutes ago",
    stats: [
      { label: "Events tracked", value: "142K" },
      { label: "Funnels monitored", value: "6" },
      { label: "Active cohorts", value: "14" },
    ],
  },
  {
    id: "datadog",
    name: "DataDog",
    description: "Advanced infrastructure observability and APM",
    bg: "bg-purple-100",
    color: "text-purple-700",
    letter: "D",
    lastSynced: "2 minutes ago",
    stats: [
      { label: "Dashboard", value: "12" },
      { label: "Monitors", value: "45" },
      { label: "Services", value: "8" },
    ],
  },
  {
    id: "mixpanel",
    name: "Mixpanel",
    description: "User journey analytics and conversion funnels",
    bg: "bg-purple-100",
    color: "text-purple-700",
    letter: "M",
    lastSynced: "5 minutes ago",
    stats: [
      { label: "Tracked users", value: "12.4K" },
      { label: "Funnels", value: "4" },
      { label: "Tickets linked", value: "3" },
    ],
  },
  {
    id: "posthog",
    name: "PostHog",
    description: "Session recordings, feature flags, heatmaps",
    bg: "bg-orange-100",
    color: "text-orange-700",
    letter: "P",
    lastSynced: "3 minutes ago",
    stats: [
      { label: "Sessions analyzed", value: "2,841" },
      { label: "Flagged sessions", value: "214" },
      { label: "Feature flags", value: "8" },
    ],
  },
  {
    id: "sentry",
    name: "Sentry",
    description: "Error tracking and performance monitoring",
    bg: "bg-red-100",
    color: "text-red-700",
    letter: "S",
    lastSynced: "1 minute ago",
    stats: [
      { label: "Active errors", value: "5" },
      { label: "Users affected", value: "3,742" },
      { label: "Occurrences (30d)", value: "5,420" },
    ],
  },
  {
    id: "github",
    name: "GitHub",
    description: "Code repository, commit history, pull requests",
    bg: "bg-slate-100",
    color: "text-slate-700",
    useIcon: true,
    lastSynced: "8 minutes ago",
    stats: [
      { label: "Repos indexed", value: "3" },
      { label: "Open PRs", value: "3" },
      { label: "Commits (30d)", value: "87" },
    ],
  },
  {
    id: "prometheus",
    name: "Prometheus",
    description: "Infrastructure metrics, service latency, uptime",
    bg: "bg-orange-100",
    color: "text-orange-600",
    letter: "Pr",
    lastSynced: "30 seconds ago",
    stats: [
      { label: "Services monitored", value: "6" },
      { label: "Metrics collected", value: "1.2K" },
      { label: "Alerts active", value: "2" },
    ],
  },
  {
    id: "slack",
    name: "Slack",
    description: "Team conversations, alerts, and incident threads",
    bg: "bg-violet-100",
    color: "text-violet-700",
    letter: "Sl",
    lastSynced: "1 minute ago",
    stats: [
      { label: "Channels monitored", value: "5" },
      { label: "Messages indexed", value: "1,639" },
      { label: "Alerts triggered", value: "3" },
    ],
  },
  {
    id: "jira",
    name: "Jira",
    description: "Tickets, sprints, and epics linked to outcomes",
    bg: "bg-blue-100",
    color: "text-blue-600",
    letter: "Ji",
    lastSynced: "4 minutes ago",
    stats: [
      { label: "Open tickets", value: "5" },
      { label: "In sprint", value: "18" },
      { label: "Blocked", value: "1" },
    ],
  },
  {
    id: "notion",
    name: "Notion",
    description: "Product specs, PRDs, and research docs",
    bg: "bg-zinc-100",
    color: "text-zinc-800",
    letter: "N",
    lastSynced: "6 hours ago",
    stats: [
      { label: "Docs synced", value: "6" },
      { label: "Databases", value: "4" },
      { label: "Linked tickets", value: "7" },
    ],
  },
];


