export type Session = {
  id: string;
  userId: string;
  startTime: string;
  duration: number;
  pageViews: string[];
  flaggedReason: string | null;
  issueType: 'rage-click' | 'dead-click' | 'drop-off' | 'repeated-navigation' | null;
  converted: boolean;
  agentAnnotation: string | null;
};

export const flaggedSessions: Session[] = [
  {
    id: 'A4821',
    userId: 'user_7h2kl9',
    startTime: '2023-12-03T14:22:11Z',
    duration: 252,
    pageViews: ['/dashboard', '/checkout', '/checkout', '/checkout'],
    flaggedReason: 'Rage-clicked "Confirm Order" 7 times before abandoning',
    issueType: 'rage-click',
    converted: false,
    agentAnnotation: 'Likely: payment timeout from payments-service v2.4.1 regression',
  },
  {
    id: 'B1043',
    userId: 'user_3n8px2',
    startTime: '2023-11-28T09:44:33Z',
    duration: 418,
    pageViews: ['/signup', '/pricing', '/signup', '/pricing', '/signup', '/pricing'],
    flaggedReason: 'Navigated to /pricing 3 times, returning from /signup each time',
    issueType: 'repeated-navigation',
    converted: false,
    agentAnnotation: 'Likely: plan confusion — pricing page does not clearly map to use case',
  },
  {
    id: 'C7720',
    userId: 'user_5m1wq8',
    startTime: '2023-11-25T16:11:02Z',
    duration: 1240,
    pageViews: ['/onboarding/1', '/onboarding/2', '/onboarding/3', '/onboarding/4', '/onboarding/5', '/dashboard'],
    flaggedReason: 'Completed 5 of 7 onboarding steps, left, returned next day, could not resume',
    issueType: 'drop-off',
    converted: false,
    agentAnnotation: 'Likely: no onboarding resume state — user lost progress',
  },
  {
    id: 'D3391',
    userId: 'user_9k4vr6',
    startTime: '2023-12-02T11:30:44Z',
    duration: 89,
    pageViews: ['/reports', '/reports', '/reports'],
    flaggedReason: 'Clicked Export CSV button 12 times with no response',
    issueType: 'dead-click',
    converted: false,
    agentAnnotation: 'Dead-click on disabled Export CSV button — PR #198 is the fix',
  },
  {
    id: 'E5512',
    userId: 'user_2b7nt4',
    startTime: '2023-12-03T09:18:22Z',
    duration: 198,
    pageViews: ['/checkout', '/dashboard', '/checkout'],
    flaggedReason: 'Abandoned checkout after 3m 18s — no error visible to user',
    issueType: 'drop-off',
    converted: false,
    agentAnnotation: 'Payment timeout — no user-facing error shown, silent failure',
  },
  {
    id: 'F8827',
    userId: 'user_6c3hr1',
    startTime: '2023-11-29T14:55:18Z',
    duration: 312,
    pageViews: ['/settings/billing', '/settings/billing', '/pricing', '/settings/billing'],
    flaggedReason: 'Returned to /settings/billing 3 times without completing upgrade',
    issueType: 'repeated-navigation',
    converted: false,
    agentAnnotation: 'Billing page UX issue — plan upgrade flow unclear',
  },
  {
    id: 'G2241',
    userId: 'user_4f9ks7',
    startTime: '2023-12-03T16:02:41Z',
    duration: 147,
    pageViews: ['/checkout'],
    flaggedReason: 'Rage-clicked Confirm Order 5 times, checkout open 2m 27s',
    issueType: 'rage-click',
    converted: false,
    agentAnnotation: 'Checkout payment timeout — payments-service regression',
  },
  {
    id: 'H9934',
    userId: 'user_1a5mk3',
    startTime: '2023-11-20T10:11:09Z',
    duration: 891,
    pageViews: ['/onboarding/1', '/onboarding/2', '/onboarding/3', '/dashboard', '/onboarding/3'],
    flaggedReason: 'Left onboarding at step 3, returned but started from step 1',
    issueType: 'drop-off',
    converted: false,
    agentAnnotation: 'No onboarding state saved — user had to restart from beginning',
  },
  {
    id: 'I4401',
    userId: 'user_8g2lp5',
    startTime: '2023-11-27T13:40:28Z',
    duration: 76,
    pageViews: ['/reports'],
    flaggedReason: 'Multiple dead clicks on Export CSV button',
    issueType: 'dead-click',
    converted: false,
    agentAnnotation: 'Same Export CSV dead-click issue as D3391 and others',
  },
  {
    id: 'J6612',
    userId: 'user_7d4hl2',
    startTime: '2023-12-04T08:22:34Z',
    duration: 234,
    pageViews: ['/checkout', '/checkout'],
    flaggedReason: 'Payment form submitted, spinner appeared, then session ended',
    issueType: 'drop-off',
    converted: false,
    agentAnnotation: 'Payment timeout — spinner with no timeout UI, user gave up',
  },
  {
    id: 'K3318',
    userId: 'user_5h8nr9',
    startTime: '2023-11-22T15:33:12Z',
    duration: 671,
    pageViews: ['/signup', '/signup', '/signup'],
    flaggedReason: 'Three signup attempts — email validation error not clearly shown',
    issueType: 'rage-click',
    converted: false,
    agentAnnotation: 'ValidationError from + alias in email — commit a3f92c regression',
  },
  {
    id: 'L8820',
    userId: 'user_3k1qm6',
    startTime: '2023-11-26T11:05:44Z',
    duration: 1180,
    pageViews: ['/pricing', '/signup', '/pricing', '/signup', '/pricing', '/dashboard'],
    flaggedReason: 'Visited pricing 3 times, eventually signed up but with low confidence',
    issueType: 'repeated-navigation',
    converted: true,
    agentAnnotation: 'Converted eventually — pricing page confusion delayed signup by ~15min',
  },
];
