export type Session = {
  id: string;
  userId: string;
  startTime: string;
  duration: number;
  pageViews: string[];
  flaggedReason: string | null;
  issueType: 'rage-click' | 'dead-click' | 'drop-off' | 'repeated-navigation' | null;
  converted: boolean;
  agentAnnotation: string | null;
  status: 'untriaged' | 'in-review' | 'triaged';
  impactScore: number;
  priority: 'P1' | 'P2' | 'P3' | null;
  linkedTicketId: string | null;
  suggestedPrompts: string[];
};

export const flaggedSessions: Session[] = [
  {
    id: 'A4821',
    userId: 'user_7h2kl9',
    startTime: '2023-12-03T14:22:11Z',
    duration: 252,
    pageViews: ['/dashboard', '/checkout', '/checkout', '/checkout'],
    flaggedReason: 'Rage-clicked "Confirm Order" 7 times before abandoning',
    issueType: 'rage-click',
    converted: false,
    agentAnnotation: 'Likely: payment timeout from payments-service v2.4.1 regression',
    status: 'untriaged',
    impactScore: 47,
    priority: null,
    linkedTicketId: null,
    suggestedPrompts: [
      'How many users hit this payment timeout this week?',
      'Which version of payments-service introduced this regression?',
      'Is there a rollback or hotfix path available?',
    ],
  },
  {
    id: 'B1043',
    userId: 'user_3n8px2',
    startTime: '2023-11-28T09:44:33Z',
    duration: 418,
    pageViews: ['/signup', '/pricing', '/signup', '/pricing', '/signup', '/pricing'],
    flaggedReason: 'Navigated to /pricing 3 times, returning from /signup each time',
    issueType: 'repeated-navigation',
    converted: false,
    agentAnnotation: 'Likely: plan confusion — pricing page does not clearly map to use case',
    status: 'untriaged',
    impactScore: 23,
    priority: null,
    linkedTicketId: null,
    suggestedPrompts: [
      'How many signups are bouncing to the pricing page during onboarding?',
      'What is the conversion rate from /pricing to /signup this month?',
      'Which plan tier is most confusing for new users?',
    ],
  },
  {
    id: 'C7720',
    userId: 'user_5m1wq8',
    startTime: '2023-11-25T16:11:02Z',
    duration: 1240,
    pageViews: ['/onboarding/1', '/onboarding/2', '/onboarding/3', '/onboarding/4', '/onboarding/5', '/dashboard'],
    flaggedReason: 'Completed 5 of 7 onboarding steps, left, returned next day, could not resume',
    issueType: 'drop-off',
    converted: false,
    agentAnnotation: 'Likely: no onboarding resume state — user lost progress',
    status: 'in-review',
    impactScore: 61,
    priority: 'P2',
    linkedTicketId: null,
    suggestedPrompts: [
      'How many users abandon onboarding mid-flow and never return?',
      'At which step do users drop off most frequently?',
      'What is the impact on activation rate if we add resume state?',
    ],
  },
  {
    id: 'D3391',
    userId: 'user_9k4vr6',
    startTime: '2023-12-02T11:30:44Z',
    duration: 89,
    pageViews: ['/reports', '/reports', '/reports'],
    flaggedReason: 'Clicked Export CSV button 12 times with no response',
    issueType: 'dead-click',
    converted: false,
    agentAnnotation: 'Dead-click on disabled Export CSV button — PR #198 is the fix',
    status: 'triaged',
    impactScore: 18,
    priority: 'P1',
    linkedTicketId: 'JIRA-1041',
    suggestedPrompts: [
      'How many users are hitting the Export CSV dead-click?',
      'What is the status of PR #198?',
      'Is there a workaround I can communicate to affected users?',
    ],
  },
  {
    id: 'E5512',
    userId: 'user_2b7nt4',
    startTime: '2023-12-03T09:18:22Z',
    duration: 198,
    pageViews: ['/checkout', '/dashboard', '/checkout'],
    flaggedReason: 'Abandoned checkout after 3m 18s — no error visible to user',
    issueType: 'drop-off',
    converted: false,
    agentAnnotation: 'Payment timeout — no user-facing error shown, silent failure',
    status: 'untriaged',
    impactScore: 39,
    priority: null,
    linkedTicketId: null,
    suggestedPrompts: [
      'How often does checkout time out with no visible error?',
      'What is the p95 latency on the payments-service endpoint?',
      'How much revenue are we losing to silent checkout failures?',
    ],
  },
  {
    id: 'F8827',
    userId: 'user_6c3hr1',
    startTime: '2023-11-29T14:55:18Z',
    duration: 312,
    pageViews: ['/settings/billing', '/settings/billing', '/pricing', '/settings/billing'],
    flaggedReason: 'Returned to /settings/billing 3 times without completing upgrade',
    issueType: 'repeated-navigation',
    converted: false,
    agentAnnotation: 'Billing page UX issue — plan upgrade flow unclear',
    status: 'untriaged',
    impactScore: 31,
    priority: null,
    linkedTicketId: null,
    suggestedPrompts: [
      'What percentage of upgrade attempts on the billing page fail to complete?',
      'What is the user drop-off rate between /pricing and /settings/billing?',
      'Which plan upgrade path has the most friction?',
    ],
  },
  {
    id: 'G2241',
    userId: 'user_4f9ks7',
    startTime: '2023-12-03T16:02:41Z',
    duration: 147,
    pageViews: ['/checkout'],
    flaggedReason: 'Rage-clicked Confirm Order 5 times, checkout open 2m 27s',
    issueType: 'rage-click',
    converted: false,
    agentAnnotation: 'Checkout payment timeout — payments-service regression',
    status: 'untriaged',
    impactScore: 47,
    priority: null,
    linkedTicketId: null,
    suggestedPrompts: [
      'How many active users are impacted by the checkout timeout regression?',
      'When did the payments-service regression first appear in logs?',
      'What is the recommended rollback commit for payments-service v2.4.1?',
    ],
  },
  {
    id: 'H9934',
    userId: 'user_1a5mk3',
    startTime: '2023-11-20T10:11:09Z',
    duration: 891,
    pageViews: ['/onboarding/1', '/onboarding/2', '/onboarding/3', '/dashboard', '/onboarding/3'],
    flaggedReason: 'Left onboarding at step 3, returned but started from step 1',
    issueType: 'drop-off',
    converted: false,
    agentAnnotation: 'No onboarding state saved — user had to restart from beginning',
    status: 'in-review',
    impactScore: 55,
    priority: 'P2',
    linkedTicketId: null,
    suggestedPrompts: [
      'How many users restart onboarding from step 1 after returning?',
      'What is the average onboarding completion time with vs without interruptions?',
      'Has anyone implemented a resume onboarding feature before — any prior art?',
    ],
  },
  {
    id: 'I4401',
    userId: 'user_8g2lp5',
    startTime: '2023-11-27T13:40:28Z',
    duration: 76,
    pageViews: ['/reports'],
    flaggedReason: 'Multiple dead clicks on Export CSV button',
    issueType: 'dead-click',
    converted: false,
    agentAnnotation: 'Same Export CSV dead-click issue as D3391 and others',
    status: 'triaged',
    impactScore: 18,
    priority: 'P1',
    linkedTicketId: 'JIRA-1041',
    suggestedPrompts: [
      'Is this the same Export CSV issue as session D3391?',
      'How many users in total have hit this dead-click?',
      'What is the ETA for the JIRA-1041 fix to ship?',
    ],
  },
  {
    id: 'J6612',
    userId: 'user_7d4hl2',
    startTime: '2023-12-04T08:22:34Z',
    duration: 234,
    pageViews: ['/checkout', '/checkout'],
    flaggedReason: 'Payment form submitted, spinner appeared, then session ended',
    issueType: 'drop-off',
    converted: false,
    agentAnnotation: 'Payment timeout — spinner with no timeout UI, user gave up',
    status: 'untriaged',
    impactScore: 42,
    priority: null,
    linkedTicketId: null,
    suggestedPrompts: [
      'How many users see the checkout spinner for more than 10 seconds?',
      'What is the average spinner duration before users abandon?',
      'What timeout threshold should we set for the payment UI?',
    ],
  },
  {
    id: 'K3318',
    userId: 'user_5h8nr9',
    startTime: '2023-11-22T15:33:12Z',
    duration: 671,
    pageViews: ['/signup', '/signup', '/signup'],
    flaggedReason: 'Three signup attempts — email validation error not clearly shown',
    issueType: 'rage-click',
    converted: false,
    agentAnnotation: 'ValidationError from + alias in email — commit a3f92c regression',
    status: 'untriaged',
    impactScore: 29,
    priority: null,
    linkedTicketId: null,
    suggestedPrompts: [
      'How many signups are failing due to the email + alias validation bug?',
      'When was commit a3f92c introduced and what else did it change?',
      'What is the fix for the + alias email validation regression?',
    ],
  },
  {
    id: 'L8820',
    userId: 'user_3k1qm6',
    startTime: '2023-11-26T11:05:44Z',
    duration: 1180,
    pageViews: ['/pricing', '/signup', '/pricing', '/signup', '/pricing', '/dashboard'],
    flaggedReason: 'Visited pricing 3 times, eventually signed up but with low confidence',
    issueType: 'repeated-navigation',
    converted: true,
    agentAnnotation: 'Converted eventually — pricing page confusion delayed signup by ~15min',
    status: 'in-review',
    impactScore: 23,
    priority: 'P3',
    linkedTicketId: null,
    suggestedPrompts: [
      'How much does pricing page confusion increase average time-to-signup?',
      'What specific plan tier information are users most likely missing?',
      'What A/B tests have been run on the pricing page in the past 6 months?',
    ],
  },
];
